### PR TITLE
Bed

### PR DESCRIPTION
**Pull request by Mani-varma1**
Includes changes that allows user to download a BED file, currently limited to a single gene bed. Connects to Variant validator and outputs the relevant information.

### CODE REVIEW

**Comment by Mani-varma1** [comment]
Currently only accepts HGNC ID

**Comment by Mani-varma1** [comment]
Now has the ability to download a bed file based on Panel ID or Rcode

**Review by OllieGYoung — APPROVED** [review]
Nice :)

**Review by Itebbs22 — APPROVED** [review]
Looks good! think the BED struggles to either generate or display when there are lots of genes in the panel (e.g. R139)?

**Review by VIBE-TG — APPROVED** [review]
It looks good

**Review by Mo-shalakani — APPROVED** [review]

**Pull request merged**
